=== calvinbui/wsd-assignment/WebContent/xsd/vehicle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML namespaces for vehicle -->
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.wsd.com/vehicle" 
	xmlns="http://www.wsd.com/vehicle"
	elementFormDefault="qualified">

	<!-- Vehicle registration in Australia is up to 6 characters. -->
	<xs:simpleType name="registration">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="6" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Vehicle must have a type -->
	<xs:simpleType name="type">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Vehicle must have a make -->
	<xs:simpleType name="make">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Vehicle must have a model -->
	<xs:simpleType name="model">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Year of vehicle mus tbe greater than 0 -->
	<xs:simpleType name="year">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Vehicle must have a colour -->
	<xs:simpleType name="colour">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Vehicle kilometres must be greater than 0 -->
	<xs:simpleType name="kilometres">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Vehicle must contain registration, type, make, model, year, colour and kilometres -->
	<xs:element name="vehicles">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="vehicle" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="registration" type="registration" />
							<xs:element name="type" type="type" />
							<xs:element name="make" type="make" />
							<xs:element name="model" type="model" />
							<xs:element name="year" type="year" />
							<xs:element name="colour" type="colour" />
							<xs:element name="kilometres" type="kilometres" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== calvinbui/wsd-assignment/WebContent/WEB-INF/vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicle xmlns="http://www.uts.edu.au/31284/vehicle"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/vehicle vehicle.xsd">

	<registration>BA30HS</registration>
	<type>Car</type>
	<make>Toyota</make>
	<model>Corolla</model>
	<year>2009</year>
	<colour>Grey</colour>
	<kilometres>60000</kilometres>
    
    <registration>AE08SM</registration>
	<type>Car</type>
	<make>Toyota</make>
	<model>Corolla</model>
	<year>1993</year>
	<colour>Red</colour>
	<kilometres>2000000</kilometres>
	
	<registration>BA30HS</registration>
	<type>Car</type>
	<make>Toyota</make>
	<model>Corolla</model>
	<year>2020</year>
	<colour>Grey</colour>
	<kilometres>60000</kilometres>
       
</vehicle>

=== calvinbui/wsd-assignment/WebContent/xml/vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- XML namespaces for vehicle, XSI and XSD -->
<vehicles
	xmlns="http://www.wsd.com/vehicle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wsd.com/vehicle xsd/vehicle.xsd">
	<vehicle>
		<registration>HOLSS1</registration>
		<type>Ute</type>
		<make>Holden</make>
		<model>SS</model>
		<year>2014</year>
		<colour>Red</colour>
		<kilometres>160</kilometres>
	</vehicle>

	<vehicle>
		<registration>FORD88</registration>
		<type>Ute</type>
		<make>Ford</make>
		<model>Falcon</model>
		<year>2008</year>
		<colour>Blue</colour>
		<kilometres>2222</kilometres>
	</vehicle>

	<vehicle>
		<registration>ODH987</registration>
		<type>Minibus</type>
		<make>Mercedes</make>
		<model>Sprinter</model>
		<year>2000</year>
		<colour>Silver</colour>
		<kilometres>222</kilometres>
	</vehicle>
	
	<vehicle>
		<registration>SN28S8</registration>
		<type>Minibus</type>
		<make>Volkswagen</make>
		<model>Kombi</model>
		<year>1992</year>
		<colour>Green</colour>
		<kilometres>22</kilometres>
	</vehicle>
	
	<vehicle>
		<registration>ABC902</registration>
		<type>Car</type>
		<make>Subaru</make>
		<model>Impreza</model>
		<year>2004</year>
		<colour>Blue</colour>
		<kilometres>221</kilometres>
	</vehicle>
	
	<vehicle>
		<registration>BA30HS</registration>
		<type>Car</type>
		<make>Toyota</make>
		<model>Corolla</model>
		<year>2009</year>
		<colour>Grey</colour>
		<kilometres>122</kilometres>
	</vehicle>
</vehicles>

=== calvinbui/wsd-assignment/WebContent/vehicle.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Style/Transform XML document using a XSL file -->
<?xml-stylesheet type="text/xsl" href="xsl/vehicle.xsl"?>

<!-- XML namespaces for vehicle, XSI and XSD -->
<vehicles
	xmlns="http://www.wsd.com/vehicle" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.wsd.com/vehicle xsd/vehicle.xsd">

	<vehicle>
		<registration>HOLSS1</registration>
		<type>Ute</type>
		<make>Holden</make>
		<model>SS</model>
		<year>2014</year>
		<colour>Red</colour>
		<kilometres>160</kilometres>
	</vehicle>

	<vehicle>
		<registration>FORD88</registration>
		<type>Ute</type>
		<make>Ford</make>
		<model>Falcon</model>
		<year>2008</year>
		<colour>Blue</colour>
		<kilometres>2222</kilometres>
	</vehicle>

	<vehicle>
		<registration>RU486A</registration>
		<type>Minibus</type>
		<make>Hyundai</make>
		<model>i30</model>
		<year>19282</year>
		<colour>White</colour>
		<kilometres>1</kilometres>
	</vehicle>

</vehicles>
